### PR TITLE
core_commands: add core chat commands

### PR DESCRIPTION
**Pull request by slook**
+ Added: Core chat commands
+ Added: clear_view() ui callback to remove gtkgui dependency for the /clear command function in chats
+ Changed: Help catagory "General" - > "Commands" and slightly improve command message descriptions

Some of the chat commands require optional arguments, so `[ ]` characters are used as placeholders instead of `< >`

The /quit mechanism requires some attention, as there are various console errors in certain scenarios.

Included some echo outputs are helpful in order to test the chat tab switching functionality, so far indicating that some core ui callbacks are lacking, such as where already joined chat room tabs do not activate as expected @mathiascode

### CODE REVIEW

**Comment by mathiascode** [comment]
Thanks for working on this. I'll look closer at the changes soon.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/e3980e27476e285e1eb57ffbf90ce61713bf425f should allow us to move forward with porting the existing commands.

**Comment by mathiascode** [comment]
> such as where already joined chat room tabs do not activate as expected

You can now use `self.core.chatrooms.show_room` to join a room or show an existing room.

**Comment by slook** [comment]
Nice job, that does work rather well... Implemented in https://github.com/mathiascode/nicotine-plus/pull/2

**Pull request merged**
